name: banknotes
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  jaguar_orm: ^2.2.6
  jaguar_query_sqflite: ^2.2.9
  photo_view: ^0.2.2
  image_picker: ^0.5.0+9
  flutter_slidable: ^0.4.9


dev_dependencies:
  flutter_test:
    sdk: flutter

  jaguar_orm_gen: ^2.2.0
  build_runner: ^0.10.0

flutter:
  uses-material-design: true
  assets:
  - resources/lang/en.json
  - resources/lang/ru.json
  - resources/images/no_image_icon.png
  - resources/images/quality.png
  - resources/images/grn1.jpg
  - resources/images/grn2.jpg
  - resources/images/grn_all.jpeg
  - resources/images/grn100.jpg
  - resources/images/grn1001.jpg
